# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf

per_listener_settings true
pid_file /run/mosquitto/mosquitto.pid

#plugin /etc/mosquitto/plugins/mosquitto_message_timestamp.so

persistence true
persistence_file mosquitto.db
persistence_location /var/lib/mosquitto/

autosave_interval 1800

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d
allow_anonymous false

listener 1883
plugin /etc/mosquitto/plugins/mosquitto_message_timestamp.so
password_file /etc/mosquitto/passwd


connection bridge-to-broker

address 192.168.6.172:1883
bridge_protocol_version mqttv50
#plugin /etc/mosquitto/plugins/mosquitto_message_timestamp.so


try_private true
cleansession false

#topic wrwo/som in 0
#topic wrwo/som/# out 1
topic pubdata/# out 2 "" wrwo/som/


remote_username ubroker1
remote_password chat

